// Generated by tools/gen-prefs-schema.js from Contents/Time Vault.kon — do not edit.
//
// The original widget declared its preferences in the .kon manifest and
// Konfabulator exposed them as preferences.<name>.value. This is that
// declaration, extracted so the shim can reproduce the same defaults.

'use strict';

globalThis.KON_PREFS_SCHEMA = {
	"lastSelectedProject": {"type":"text","defaultValue":"1","hidden":true},
	"lastRightPartWidth": {"type":"text","defaultValue":"setme","hidden":true},
	"lastDrawerHeight": {"type":"text","defaultValue":"300","hidden":true},
	"windowLocation": {"type":"text","defaultValue":"setme","hidden":true},
	"lastDrawerWidth": {"type":"text","defaultValue":"setme","hidden":true},
	"lastSelectedProjectID": {"type":"text","defaultValue":"setme","hidden":true},
	"lastSelectedTaskID": {"type":"text","defaultValue":"setme","hidden":true},
	"showArchivedProjects": {"type":"text","defaultValue":"0","hidden":true},
	"locale": {"type":"popup","defaultValue":"default","option":["Default","Français (French)","English (English)","Türkçe (Turkish)"],"optionValue":["default","fr","en","tr"]},
	"expandStyle": {"type":"popup","defaultValue":"1"},
	"enableAutoSave": {"type":"checkbox","defaultValue":"1"},
	"restartOnProjectChange": {"type":"checkbox","defaultValue":"0"},
	"useTrayIcon": {"type":"checkbox","defaultValue":"0","hidden":true},
	"checkForNewVersion": {"type":"checkbox","defaultValue":"1"},
	"colorScheme": {"type":"popup","defaultValue":"4","group":"skin"},
	"glassColor1": {"type":"color","defaultValue":"#0d68ff","group":"skin"},
	"glassColor2": {"type":"color","defaultValue":"#0948b1","group":"skin"},
	"headerFontColor": {"type":"color","defaultValue":"#ffffff","hidden":true},
	"normalFontColor": {"type":"color","defaultValue":"#ffffff","hidden":true},
	"numberDateFormat": {"type":"popup","defaultValue":"0","group":"time","option":["31/12/2007","12/31/2007"],"optionValue":["0","1"]},
	"useAmpm": {"type":"checkbox","defaultValue":"0","group":"time"},
	"dataFolder": {"type":"selector","defaultValue":"setme","group":"report"},
	"publishReports": {"type":"checkbox","defaultValue":"1","group":"report"},
	"reportColumn0": {"type":"popup","defaultValue":"1","group":"report"},
	"reportColumn1": {"type":"popup","defaultValue":"2","group":"report"},
	"reportColumn2": {"type":"popup","defaultValue":"3","group":"report"},
	"reportColumn3": {"type":"popup","defaultValue":"0","group":"report"},
	"reportColumn4": {"type":"popup","defaultValue":"0","group":"report"},
	"reportColumn5": {"type":"popup","defaultValue":"0","group":"report"},
	"reportColumn6": {"type":"popup","defaultValue":"0","group":"report"},
	"publishDailyReports": {"type":"checkbox","defaultValue":"1","group":"report"},
	"reportDataDelimiter": {"type":"text","defaultValue":",","group":"report"},
	"joplinSyncEnabled": {"type":"checkbox","defaultValue":"0","group":"joplin","title":"Sync to Joplin","description":"Writes your projects and entries to a \"Time Vault\" notebook after each timed entry. One-way: those notes are rewritten every time, so any changes made in Joplin are lost. Joplin must be running with the Web Clipper service enabled."},
};

globalThis.KON_PREF_GROUPS = {
	"skin": {
		"icon": "Resources/SkinIcon.png"
	},
	"time": {
		"icon": "Resources/TimeIcon.png"
	},
	"report": {
		"icon": "Resources/ReportIcon.png"
	},
	"joplin": {
		"icon": "",
		"title": "Joplin"
	}
};
